# force loading even when hidden
outputOptions(output, "dynamicLearners",     suspendWhenHidden = FALSE)
outputOptions(output, "learner_amount",      suspendWhenHidden = FALSE)
outputOptions(output, "tasktype",            suspendWhenHidden = FALSE)
outputOptions(output, "datasetPlot",         suspendWhenHidden = FALSE)
outputOptions(output, "taskSelection",       suspendWhenHidden = FALSE)
outputOptions(output, "min_max_modals_1",    suspendWhenHidden = FALSE)
outputOptions(output, "min_max_modals_2",    suspendWhenHidden = FALSE)
outputOptions(output, "dynamicParameters_1", suspendWhenHidden = FALSE)
outputOptions(output, "dynamicParameters_2", suspendWhenHidden = FALSE)
outputOptions(output, "showLearners",        suspendWhenHidden = FALSE)
outputOptions(output, "showParam1",          suspendWhenHidden = FALSE)
outputOptions(output, "showParam2",          suspendWhenHidden = FALSE)
